### ISSUE TITLE
hello..!

### ISSUE THREAD

**Issue by dizzyplay** [arzg/eldiro#1]
I enjoyed your article very much...!
It was vague to create a language to me, but I was inspired by your article.
There seems to be no update after the post has been serialized several times within a short period of time.
I don't want to put pressure on you, but I would appreciate it if you notice there are readers waiting.

Thank you again for your work.

**Comment by arzg** [comment]
> I enjoyed your article very much...!
> It was vague to create a language to me, but I was inspired by your article.

Thank you :)

> There seems to be no update after the post has been serialized several times within a short period of time.
> I don't want to put pressure on you, but I would appreciate it if you notice there are readers waiting.

I’m glad to hear that I’ve made something people like to read! I’ve been working on some other projects ([Fjord](https://github.com/arzg/fjord), [pt](https://github.com/arzg/pt) and [Polyp](https://github.com/arzg/polyp)) recently, so I haven’t been writing any posts. After seeing your comment I decided to spend a couple hours writing and editing, so thanks to you I’ve published the [fourth part](https://arzg.github.io/lang/4/).

**Comment by arzg** [comment]
If you hadn’t opened this issue I’m not sure how long it would have taken me to get around to writing the post, so I’m really grateful :)

**Comment by dizzyplay** [comment]
wow!! I was surprised that the answer was quick!
Perhaps other readers were also waiting for the next episode except me.
and I am happy to be able to keep following the blog post.
thank you!!!

**Comment by arzg** [comment]
Sorry for the notification, but can I close this issue?

**Comment by dizzyplay** [comment]
sure!
