### ISSUE TITLE
Adding git tags for when each blog post is released

### ISSUE THREAD

**Issue by SeanMcLoughlin** [arzg/eldiro#4]
Hi,

First I'd like to say thanks for taking the time to make this blog series. 

I'd like to see the code at the time of writing a specific post, but that requires me to search through the repo's history and make a guess as to which commit corresponds with when that blog post was posted. Would it be possible to use git tags to tag the commit of the repo when you post a new blog post? That way, myself and others could just checkout the repo at that tag to browse the code.

**Comment by arzg** [comment]
Great idea! I’ll add them now.
