### ISSUE TITLE
Part Three typo

### ISSUE THREAD

**Issue by cgyurgyik** [arzg/eldiro#5]
> remove `mod util`; from `expr.rs`, and put the following in `lib.rs`:

Should be

> remove `mod utils`; from `expr.rs`, and put the following in `lib.rs`:

i.e. `mod util` -> `mod utils`

Thanks for the series!

**Comment by arzg** [comment]
Thanks for spotting this! I’ll fix it now.

**Comment by arzg** [comment]
[Done](https://github.com/arzg/website/commit/12b378745868de3f91457ab685e997b377532442).
